apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: webserver
  namespace: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vintageblue-ng-deployment
  minReplicas: 3
  maxReplicas: 30
  targetCPUUtilizationPercentage: 70

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wasserver
  namespace: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: vintageblue-tc-deployment
  minReplicas: 3
  maxReplicas: 30
  targetCPUUtilizationPercentage: 70
